export const INITIAL_DRIVERS = [
{ id: 'd1', name: 'Delgadillo', license: 'CDL-A', status: 'available', avatar: 'DE' },
{ id: 'd2', name: 'Ochoa', license: 'CDL-A', status: 'available', avatar: 'OC' },
{ id: 'd3', name: 'R.D. Garcia', license: 'CDL-A', status: 'available', avatar: 'RG' },
{ id: 'd4', name: 'Vazquez', license: 'CDL-A', status: 'available', avatar: 'VA' },
{ id: 'd5', name: 'Figueroa', license: 'CDL-A', status: 'available', avatar: 'FI' },
{ id: 'd6', name: 'Varela', license: 'CDL-A', status: 'available', avatar: 'VR' },
{ id: 'd7', name: 'Carrillo', license: 'CDL-A', status: 'available', avatar: 'CA' },
{ id: 'd8', name: 'Dominguez', license: 'CDL-A', status: 'available', avatar: 'DO' },
{ id: 'd9', name: 'Ruiz', license: 'CDL-A', status: 'available', avatar: 'RU' },
{ id: 'd10', name: 'Ucclop', license: 'CDL-A', status: 'available', avatar: 'UC' },
{ id: 'd11', name: 'Sanchez', license: 'CDL-A', status: 'available', avatar: 'SA' },
{ id: 'd12', name: 'Flores', license: 'CDL-A', status: 'available', avatar: 'FL' },
{ id: 'd13', name: 'Barraza', license: 'CDL-A', status: 'available', avatar: 'BA' },
{ id: 'd14', name: 'Burgos', license: 'CDL-A', status: 'available', avatar: 'BU' },
{ id: 'd15', name: 'Ospina', license: 'CDL-A', status: 'available', avatar: 'OS' },
{ id: 'd16', name: 'Michael', license: 'CDL-A', status: 'available', avatar: 'MI' },
{ id: 'd17', name: 'Mendez', license: 'CDL-A', status: 'available', avatar: 'ME' },
{ id: 'd18', name: 'Martinez', license: 'CDL-A', status: 'available', avatar: 'MA' },
{ id: 'd19', name: 'Corey Hdz', license: 'CDL-A', status: 'available', avatar: 'CH' },
{ id: 'd20', name: 'Ebron', license: 'CDL-A', status: 'available', avatar: 'EB' },
{ id: 'd21', name: 'Diaz', license: 'CDL-A', status: 'available', avatar: 'DI' },
{ id: 'd22', name: 'Saez', license: 'CDL-A', status: 'available', avatar: 'SZ' },
{ id: 'd23', name: 'Rodriguez', license: 'CDL-A', status: 'available', avatar: 'RO' },
{ id: 'd24', name: 'Joshua H', license: 'CDL-A', status: 'available', avatar: 'JH' },
{ id: 'd25', name: 'Gutierrez', license: 'CDL-A', status: 'available', avatar: 'GU' },
{ id: 'd26', name: 'Antuna', license: 'CDL-A', status: 'available', avatar: 'AN' },
{ id: 'd27', name: 'Tarango', license: 'CDL-A', status: 'available', avatar: 'TA' },
{ id: 'd28', name: 'Sierra', license: 'CDL-A', status: 'available', avatar: 'SI' },
{ id: 'd29', name: 'Chavez', license: 'CDL-A', status: 'available', avatar: 'CZ' }
];


export const INITIAL_TRUCKS = [
{ id: 't427', plate: '427', type: 'Truck', status: 'available', capacity: 'Standard' },
{ id: 't1046', plate: '1046', type: 'Truck', status: 'available', capacity: 'Standard' },
{ id: 't1047', plate: '1047', type: 'Truck', status: 'available', capacity: 'Standard' },
{ id: 't1065', plate: '1065', type: 'Truck', status: 'available', capacity: 'Standard' },
{ id: 't1082', plate: '1082', type: 'Truck', status: 'available', capacity: 'Standard' },
{ id: 't4037', plate: '4037', type: 'Truck', status: 'available', capacity: 'Standard' },
{ id: 't4064', plate: '4064', type: 'Truck', status: 'available', capacity: 'Standard' },
{ id: 't4079', plate: '4079', type: 'Truck', status: 'available', capacity: 'Standard' },
{ id: 't4080', plate: '4080', type: 'Truck', status: 'available', capacity: 'Standard' },
{ id: 't4082', plate: '4082', type: 'Truck', status: 'available', capacity: 'Standard' },
{ id: 't4098', plate: '4098', type: 'Truck', status: 'available', capacity: 'Standard' },
{ id: 't4099', plate: '4099', type: 'Truck', status: 'available', capacity: 'Standard' },
{ id: 't4113', plate: '4113', type: 'Truck', status: 'available', capacity: 'Standard' },
{ id: 't4115', plate: '4115', type: 'Truck', status: 'available', capacity: 'Standard' },
{ id: 't4124', plate: '4124', type: 'Truck', status: 'available', capacity: 'Standard' },
{ id: 't4127', plate: '4127', type: 'Truck', status: 'available', capacity: 'Standard' },
{ id: 't4132', plate: '4132', type: 'Truck', status: 'available', capacity: 'Standard' },
{ id: 't4134', plate: '4134', type: 'Truck', status: 'available', capacity: 'Standard' },
{ id: 't4145', plate: '4145', type: 'Truck', status: 'available', capacity: 'Standard' },
{ id: 't4146', plate: '4146', type: 'Truck', status: 'available', capacity: 'Standard' },
{ id: 't4147', plate: '4147', type: 'Truck', status: 'available', capacity: 'Standard' },
{ id: 't4153', plate: '4153', type: 'Truck', status: 'available', capacity: 'Standard' },
{ id: 't4155', plate: '4155', type: 'Truck', status: 'available', capacity: 'Standard' },
{ id: 't4156', plate: '4156', type: 'Truck', status: 'available', capacity: 'Standard' },
{ id: 't4157', plate: '4157', type: 'Truck', status: 'available', capacity: 'Standard' },
{ id: 't4161', plate: '4161', type: 'Truck', status: 'available', capacity: 'Standard' },
{ id: 't4164', plate: '4164', type: 'Truck', status: 'available', capacity: 'Standard' },
{ id: 't4166', plate: '4166', type: 'Truck', status: 'available', capacity: 'Standard' },
{ id: 't4167', plate: '4167', type: 'Truck', status: 'available', capacity: 'Standard' },
];